name: "Create multi-arch docker image"
inputs:
  registry:
    required: true
    description: "Image registry FQDN"
  username:
    required: true
    description: "Login username for the registry"
  password:
    required: true
    description: "Login password for the registry"
  image:
    required: true
    description: "Image tag"
  image-version:
    required: true
    description: "Image version"
runs:
  using: "composite"
  steps:
    - name: Login to the registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Create multi-arch image manifest
      shell: bash
      run: |
        IMAGE=${{ inputs.image }}:${{ inputs.image-version }}
        docker manifest create ${IMAGE} \
            ${IMAGE}-amd64 \
            ${IMAGE}-arm64
        docker manifest push ${IMAGE}
        docker manifest create ${{ inputs.image }}:latest \
            ${{ inputs.image }}:latest-amd64 \
            ${{ inputs.image }}:latest-arm64
        docker manifest push ${{ inputs.image }}:latest

    # - name: Create multi-arch image manifest with tag "2022"
    #   shell: bash
    #   run: |
    #     IMAGE=${{ inputs.image }}:${{ inputs.image-version }}
    #     docker manifest create ${IMAGE}-2022 \
    #         ${IMAGE}-amd64-2022 \
    #         ${IMAGE}-arm64-2022
    #     docker manifest push ${IMAGE}-2022
    #     docker manifest create ${{ inputs.image }}:2022 \
    #         ${{ inputs.image }}:2022-amd64 \
    #         ${{ inputs.image }}:2022-arm64
    #     docker manifest push ${{ inputs.image }}:2022