name: Create manifest

on: [ workflow_dispatch ]

jobs:
  manifest:
    runs-on: ubuntu-20.04
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: -1
      - name: create tag
        run: |
          echo "IMAGE_VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - uses: ./.github/actions/create-multi-arch-image
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/being24/latex-docker
          image-version: ${{ env.IMAGE_VERSION }}
      - uses: ./.github/actions/create-multi-arch-image
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: ${{ secrets.DOCKERHUB_USERNAME }}/latex-docker
          image-version: ${{ env.IMAGE_VERSION }}
      - name: Create GitHub Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=v$(cat VERSION)
          if git show-ref --tags | grep -q "refs/tags/${TAG}"
          then
            echo "${TAG} exists. Skipped"
            exit 0
          fi
          git tag ${TAG}
          git push --tags
          gh release create ${TAG} -n "${TAG}"